version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: price-app
        ports:
            - "8003:80"
        volumes:
            - .:/var/www/html
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
